# Generated by Django 5.2.12 on 2026-03-06 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('objective', models.CharField(blank=True, max_length=255, null=True)),
                ('target_audience', models.TextField(blank=True, null=True)),
                ('offer_summary', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=30)),
                ('daily_send_limit', models.PositiveIntegerField(default=50)),
                ('follow_up_gap_days', models.PositiveIntegerField(default=3)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='workspace.workspace')),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
                'unique_together': {('workspace', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CampaignLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('contacted', 'Contacted'), ('replied', 'Replied'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('meeting_booked', 'Meeting Booked'), ('completed', 'Completed')], default='pending', max_length=30)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_leads', to='campaigns.campaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_campaigns', to='leads.lead')),
            ],
            options={
                'db_table': 'campaign_leads',
                'ordering': ['-created_at'],
                'unique_together': {('campaign', 'lead')},
            },
        ),
        migrations.CreateModel(
            name='CampaignSequenceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('step_type', models.CharField(choices=[('initial', 'Initial Email'), ('follow_up', 'Follow Up')], default='follow_up', max_length=20)),
                ('delay_days', models.PositiveIntegerField(default=0)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_steps', to='campaigns.campaign')),
            ],
            options={
                'db_table': 'campaign_sequence_steps',
                'ordering': ['step_number'],
                'unique_together': {('campaign', 'step_number')},
            },
        ),
    ]
