# Generated by Django 5.2.12 on 2026-03-06 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('leads', '0001_initial'),
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGeneratedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('initial', 'Initial'), ('follow_up', 'Follow Up'), ('custom', 'Custom')], default='initial', max_length=30)),
                ('input_prompt', models.TextField(blank=True, null=True)),
                ('generated_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('generated_body', models.TextField()),
                ('variables_snapshot', models.JSONField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_generated_messages', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generated_messages', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_generated_messages', to='leads.lead')),
                ('sequence_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_messages', to='campaigns.campaignsequencestep')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generated_messages', to='workspace.workspace')),
            ],
            options={
                'db_table': 'ai_generated_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIProviderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI')], default='openai', max_length=50)),
                ('api_key', models.CharField(max_length=500)),
                ('model_name', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_provider_setting', to='workspace.workspace')),
            ],
            options={
                'db_table': 'ai_provider_settings',
            },
        ),
    ]
